from fpdf import FPDF

pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)

pdf.add_page()
pdf.set_font('Helvetica', 'B', 20)
pdf.cell(0, 10, 'MERN Stack Explained', ln=True, align='C')
pdf.ln(10)
pdf.set_font('Helvetica', '', 12)
pdf.multi_cell(0, 8, 'This document provides a concise, clear explanation of the MERN stack and how its components work together.')

pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.cell(0, 10, '1. What is MERN Stack?', ln=True)
pdf.set_font('Helvetica', '', 12)
pdf.ln(4)
pdf.multi_cell(0, 8, 'MERN is an acronym for four technologies used together to build full-stack web applications: MongoDB, Express.js, React.js, and Node.js. It is a popular JavaScript-based stack for building scalable and maintainable web apps.')

pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.cell(0, 10, '2. Components of MERN', ln=True)
pdf.set_font('Helvetica', '', 12)
pdf.ln(4)
pdf.multi_cell(0, 8, 'MongoDB: A NoSQL document database that stores application data in JSON-like documents. It allows flexible and scalable data storage for modern web apps.')
pdf.ln(4)
pdf.multi_cell(0, 8, 'Express.js: A lightweight web application framework for Node.js. It simplifies building web servers, APIs, and handling HTTP requests and responses.')
pdf.ln(4)
pdf.multi_cell(0, 8, 'React.js: A front-end library for building user interfaces with reusable components. React manages the view layer and renders dynamic UI in the browser.')
pdf.ln(4)
pdf.multi_cell(0, 8, 'Node.js: A JavaScript runtime environment for running server-side code. It uses a non-blocking event-driven model, making it suitable for scalable applications.')

pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.cell(0, 10, '3. How MERN Works Together', ln=True)
pdf.set_font('Helvetica', '', 12)
pdf.ln(4)
pdf.multi_cell(0, 8, 'A MERN application typically has a React front end that communicates with an Express/Node.js backend via HTTP and REST APIs. The backend handles requests, business logic, and data access, while MongoDB stores and retrieves application data.')
pdf.ln(4)
pdf.multi_cell(0, 8, 'In this stack, JavaScript is used across both client and server, making development more consistent and easier to manage. The data flows from the browser to the server and then to the database, and back as JSON.')

pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.cell(0, 10, '4. Typical MERN Features', ln=True)
pdf.set_font('Helvetica', '', 12)
pdf.ln(4)
pdf.multi_cell(0, 8, 'Common features of a MERN app include user authentication, CRUD operations (Create, Read, Update, Delete), state management, REST APIs, responsive UI, and database persistence.')
pdf.ln(4)
pdf.multi_cell(0, 8, 'Developers often use additional tools like Redux for state management, Mongoose for MongoDB object modeling, and middleware for authentication and error handling.')

pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.cell(0, 10, '5. Benefits of MERN', ln=True)
pdf.set_font('Helvetica', '', 12)
pdf.ln(4)
pdf.multi_cell(0, 8, '1. Full JavaScript development across the stack.')
pdf.ln(2)
pdf.multi_cell(0, 8, '2. Large ecosystem and strong community support.')
pdf.ln(2)
pdf.multi_cell(0, 8, '3. Fast development with reusable components and ready-made libraries.')
pdf.ln(2)
pdf.multi_cell(0, 8, '4. Easy integration between front end, backend, and database.')

pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.cell(0, 10, '6. Example Workflow', ln=True)
pdf.set_font('Helvetica', '', 12)
pdf.ln(4)
pdf.multi_cell(0, 8, 'A typical MERN workflow may look like:')
pdf.ln(4)
pdf.multi_cell(0, 8, '1. The browser sends a request to the Express server through a React front end.')
pdf.ln(2)
pdf.multi_cell(0, 8, '2. Express.js handles routing and middleware, then passes the request to Node.js application code.')
pdf.ln(2)
pdf.multi_cell(0, 8, '3. Node.js executes server-side logic and uses MongoDB to store or retrieve data.')
pdf.ln(2)
pdf.multi_cell(0, 8, '4. The server sends a JSON response back to React, which updates the UI.')

pdf.output('mern_stack_explained.pdf')
print('Created mern_stack_explained.pdf')
